=== Ilamparithi-070/All-Sports/post.dtd
<!ELEMENT post_all (post+)>
<!ELEMENT post (date+,title,link,content)>
<!ELEMENT date (month,day,year)>
<!ELEMENT day (#PCDATA)>
<!ELEMENT month (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT link (#PCDATA)>
<!ELEMENT content (#PCDATA)>
<!ATTLIST content type CDATA "long_text">
<!ATTLIST content type CDATA "video">
<!ATTLIST content type CDATA "image">
<!ATTLIST content type CDATA "short_text">

=== Ilamparithi-070/All-Sports/post.xml
<?xml version="1.0" encoding="UTF-16"?>
<!DOCTYPE post_all SYSTEM "post.dtd">
<post_all>
	<post>
		<date> 
			<month> September</month>
			<day> 08</day>
			<year> 2022</year>
		</date>
		<title> World Cup Announced! </title>
		<link> http://linkhere.com </link>
		<content type="text"> The dates for the upcoming 2023 world cup has been released</content>
	</post>
</post_all>
